site_name: Tushar Dhyani
site_description: Tushar Dhyani's website
site_url: https://tushardhyani.com/
theme:
  name: material
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-4
        name: Dark mode
      primary: black
      accent: deep_orange

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-7
        name: Light mode
      primary: white
      accent: light_blue

plugins:
  - search
  - blog

markdown_extensions:
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight:
      anchor_linenums: false
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true 
  # Math support in md
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  # - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  # - https://polyfill.io/v3/polyfill.min.js?features=es6
  # - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
      

extra:
  generator: false # To remove the made with Material for MkDocs line from footer.
  social:
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/in/tushar-dhyani/
    - icon: fontawesome/brands/github 
      link: https://github.com/Thanatoz-1/
    - icon: fontawesome/brands/kaggle
      link: https://kaggle.com/thanatoz
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/t_dhyani
    - icon: fontawesome/brands/instagram 
      link: https://instagram.com/thanatoz_1
    