authors:
  thanatoz:
    name: Tushar Dhyani        # Author name
    description: My description will go here # Author description
    avatar: https://github.com/squidfunk.png         # Author avatar
  squidfunk:
    name: Martin Donath
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/932156
  alexvoss:
    name: Alex Voss
    description: Community support
    avatar: https://avatars.githubusercontent.com/u/4134224