name: page_ci 
on:
  push:
    branches:
      - master 
      - main
env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material 
      - run: pip install mkdocs-rss-plugin
      - run: pip install mkdocs-blogging-plugin
      - run: mkdocs gh-deploy --force
